
export const GET_ARTICLES_START = "GET_ARTICLES_START";
export const GET_ARTICLES_SUCCESS = "GET_ARTICLES_SUCCESS";
export const GET_ARTICLES_ERROR = "GET_ARTICLES_ERROR";
export const GET_ARTICLE_START = "GET_ARTICLE_START";
export const GET_ARTICLE_SUCCESS = "GET_ARTICLE_SUCCESS";
export const GET_ARTICLE_ERROR = "GET_ARTICLE_ERROR";
export const ADD_ARTICLE = "ADD_ARTICLE";
export const ADD_ARTICLE_ERROR = "ADD_ARTICLE_ERROR";
export const REMOVE_ARTICLE = "REMOVE_ARTICLE";
export const REMOVE_ARTICLE_ERROR = "REMOVE_ARTICLE_ERROR";
export const EDIT_ARTICLE = "EDIT_ARTICLE";
export const EDIT_ARTICLE_ERROR = "EDIT_ARTICLE_ERROR";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

